CREATE TABLE MEMBER( // USER로 만들기 안됨 -> 대체해야 될 것 같음 ex.) MEMBER
    MEMBER_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(10) NOT NULL,
    ID CHAR(14) NOT NULL UNIQUE,
    PWD VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    IS_ADMIN CHAR(1) DEFAULT 'N' CHECK(IS_ADMIN IN('Y', 'N')),
    STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN('Y', 'N')),
    JOIN_DATE DATE DEFAULT SYSDATE
);
CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_GENRE VARCHAR2(5) NOT NULL,
    WRITER NUMBER NOT NULL,
    TITLE VARCHAR2(60) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY(WRITER) REFERENCES MEMBER
);

CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    WRITER NUMBER NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    CONTENT VARCHAR2(200) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'N' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY(WRITER) REFERENCES MEMBER,
    FOREIGN KEY(BOARD_NO) REFERENCES BOARD
);

CREATE TABLE RECIPE(
    RECIPE_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    INTRO VARCHAR2(30),
    NATION VARCHAR2(20) NOT NULL,
    difficulty VARCHAR2(10) NOT NULL,
    INGREDIENTS VARCHAR2(50) NOT NULL,
    FOREIGN KEY(BOARD_NO) REFERENCES BOARD
);

CREATE TABLE IMAGE(
    IMAGE_NO NUMBER PRIMARY KEY,
    RECIPE_NO NUMBER NOT NULL,
    IMAGE_URL CHAR(14) UNIQUE,
    IMAGE_NAME NUMBER NOT NULL,
    TITLE_IMG NUMBER DEFAULT 1 CHECK(TITLE_IMG IN(1, 0)),
    FOREIGN KEY(RECIPE_NO) REFERENCES IMAGE
);

CREATE SEQUENCE SEQ_MEMBER START WITH 100 NOCACHE; -- 유저번호는 100번부터 시작
CREATE SEQUENCE SEQ_BOARD NOCACHE;
CREATE SEQUENCE SEQ_REPLY NOCACHE;
CREATE SEQUENCE SEQ_RECIPE NOCACHE;
CREATE SEQUENCE SEQ_IMAGE NOCACHE;

-- MEMBER-BOARD VIEW: 멤버 ID를 받아와 BOARD 보여줘야 하니까? -> 필요없을수도?.. WRITER에 들어있어서
-- BOARD-RECIPE-IMAGE VIEW: 한번에 3군데에 있는 칼럼들을 뽑아야 하니까?
